### ISSUE TITLE
[BUG]Out Of Memory

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#235] opened 2019-05-26 06:55 UTC
**Describe the bug**
OB keep crashing with the same error and so annoying 

**To Reproduce**
I think happens when lot retries more than 500k, for configs which bans lot retries are normal in big wordlists, but seems OB cant handle it https://i.imgur.com/LAuGRtt.png

**Version**
 - Commit 206

**Comment by openbullet** [comment] 2019-05-26 08:39
What are your specs?

**Comment by mastercho** [comment] 2019-05-26 09:00
32 GB RAM DDR4, I7 8750H 2.20GHZ , 2TB SSD, GTX 1070  Win 10 x64,

**Comment by openbullet** [comment] 2019-05-26 23:22
I need to know where it happens, because I cannot reproduce it. Try running OB from visual studio and see where the exception is generated please (and if you have a memory profiler please use it and check if there are too many instances of an object).

**Comment by mastercho** [comment] 2019-05-26 23:24
Thing is happening random, running all day still not crashed. But retries did not exceed 500k - 1BN yet. It happens on when got lot retries + my all logs are enabled.

**Comment by openbullet** [comment] 2019-05-26 23:28
HAH, that's why. Disable logs for the love of god please. The program logs are only meant for debugging, NEVER use them while running as they are not buffered in a FIFO style yet (like meinname asked here https://github.com/openbullet/openbullet/issues/168). So just wait for that issue to be solved if you really want to keep logs enabled. I will close this.

**Closed by openbullet** 2019-05-26 23:28 UTC
Labels: bug
