### ISSUE TITLE
Each runner should have its own proxy

### ISSUE THREAD

**Issue by walkingatm** [openbullet/openbullet#692] opened 2020-05-23 17:41 UTC
Each runner should be able to have it own proxy to run,,,, not to share same proxy with all runners

**Comment by openbullet** [comment] 2020-05-23 18:57
This is a duplicate of another issue I cannot find and anyways I just implemented this in OB2 so wait for OB2 release if you want to use this feature

**Closed by openbullet** 2020-05-23 18:57 UTC
