### ISSUE TITLE
[BUG] After update I get "Error while converting..."

### ISSUE THREAD

**Issue by Derp0** [openbullet/openbullet#456] opened 2020-01-05 13:26 UTC
**Describe the bug**
After update to version 1.1.5 I get a lot of "Error converting to blocks, please check the syntax!"
With reasons such as "Invalid '<block> name'" or "Object reference not set..."

Really odd that it shows error for some configs built with version 1.1.4 but not all of them.

**Version**
1.1.5

**Comment by openbullet** [comment] 2020-01-06 02:56
It's probably caused by this
https://github.com/openbullet/openbullet/commit/7de6ff20b0661b3484619a91481e23bf5ca5b859
Find where it says `ParseQuery=True` in the LoliScript code and remove it.

**Comment by Derp0** [comment] 2020-01-06 13:21
So, `ParseQuery` key has been changed to `AcceptEncoding`?
Can you please add a way to auto-correct such errors?

And what about functions? Their name has been changed as well? I get an error for `FUNCTION RSA` too.

Also a small problem which I don't think needs a separate issue is the proxy checker. When `Only Untested` is checked it checks the tested proxies as well, shouldn't it only check the untested ones?

**Comment by openbullet** [comment] 2020-01-06 18:32
No, ParseQuery was removed, it wasn't changed with anything else. I agree that there should be a system to avoid those errors, yeah. I will keep this issue open so I don't forget.

All the crypto functions were reworked as they were lacking and not working, so any config using the crypto functions that were changed was not working for sure, hence there should be no problem with that since no one was using them in the first place. They were broken from the start.

The proxy checker has been fixed on the develop branch so just wait for the merge ok?

**Comment by Derp0** [comment] 2020-01-06 20:11
May I ask why? I mean I don't really know what it did in the first place, but don't some configs that use it need it?

I don't quite get that, you mean to say they were added as some kind of a placeholder and them being there or not wouldn't have made any difference?
And should I remove the whole block or replace it with an appropriate new function? I guess in the case above it would be `FUNCTION RSADecrypt`?

OK, no hurry. Thanks.

**Comment by openbullet** [comment] 2020-01-08 10:22
It didn't do anything that the main library wasn't already doing, that's why it got removed.

For the RSADecrypt you sure need to use the new function.

The auto-save is only done in memory and not on the actual file, so if you don't click on the save icon the file shouldn't be overwritten, but yeah I understand and fixing that would need a separate issue.

**Comment by openbullet** [comment] 2020-02-22 04:01
I removed the error when a boolean does not exist anymore, now it's just disregarded and there's no error shown, the change is on dev branch.

**Closed by openbullet** 2020-02-22 04:01 UTC

**Comment by Derp0** [comment] 2020-02-23 15:56
I think a warning would be better than disregarding it, less cluttered code this way. Or just highlighting/underlining them in the Script editor.

How long should I expect till it's released?

**Comment by openbullet** [comment] 2020-02-23 18:45
That's too advanced for the current scope of the language, warnings / errors and such would require a lot of work and I don't want to put myself through all that work.

The fix will be included in the next merge which will happen next month.
