### ISSUE TITLE
Proxy auth

### ISSUE THREAD

**Issue by Fyse** [openbullet/openbullet#14] opened 2019-04-03 19:39 UTC
I’m attempting to enter proxies with auth into the advanced proxy settings box using the correct syntax, although when testing my proxies they appear not be working on Open Bullet even though I’ve checked they’re online.

**Comment by kdog2018** [comment] 2019-04-04 11:43
also when I import them with the copy box and select socks4 after pasting still puts them in http field

**Comment by btri92** [comment] 2019-04-05 13:25
123.123.123.123:80  user: xxxxx  - pass: xxxx . How to run the proxy has user and pass .

**Comment by openbullet** [comment] 2019-04-05 16:48
@kdog2018 That has been fixed in a previous commit.
I will try using proxies with auth and fix the issue.

**Comment by openbullet** [comment] 2019-04-05 18:03
Guys I can confirm auth proxies are working, I just tested. Example
(http)127.0.0.1:8888:username:password
Remember to put (http) or the other protocols at the start of the line! Otherwise it won't parse it using advanced mode ^_^ Remember that in order to use Proxy Chains or proxies with Auth you MUST paste them inside the box, do not load them from file because it won't work!

**Closed by openbullet** 2019-04-05 18:03 UTC

**Comment by Fyse** [comment] 2020-05-15 20:50
Hey, sorry to open this up again. Just had a question as I can't seem to get this working - is there support for auth proxies in selenium?

**Comment by meinname** [comment] 2020-05-15 22:34
There is already an issue with proxy auth and selenium:
https://github.com/openbullet/openbullet/issues/394

**Comment by mamamiia** [comment] 2021-12-28 00:08
There is already an issue with proxy auth and selenium
plz fix it

**Comment by mamamiia** [comment] 2021-12-28 00:08
There is already an issue with proxy auth and selenium

**Comment by openbullet** [comment] 2021-12-28 09:17
@mamamiia this project is discontinued, please switch to OB2
