### ISSUE TITLE
[BUG] DBC Update

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#203] opened 2019-05-14 01:17 UTC
**Describe the bug**
DBC updated their API and now returns this message

```
Unable to complete request. Check your account credentials, balance, and ensure you're using the API correctly.
 If you're receiving this message on our API, please check in our website for Updates notices.
If this problem persists, please contact support at help@deathbycaptcha.eu.
We appreciate your patience and understanding!
```

On Balance check

**To Reproduce**
1. Add DBC acc and click balance check

**Version**
 - Version 1.1.2

**Comment by meinname** [comment] 2019-05-14 14:47
DBC Still works for me:
<img width="1661" alt="image" src="https://user-images.githubusercontent.com/16181408/57707435-ef4caf00-7667-11e9-9285-63610e0fcad8.png">

**Comment by mastercho** [comment] 2019-05-14 15:12
Asked yesterday others and they seem have the same issue, but now when checking i got this response 

`status=0&is_banned=0&balance=48.513&rate=0.879&user=9687` and seems OB doesn't recognize this response lol

**Comment by openbullet** [comment] 2019-05-17 19:43
Closing since no one else can reproduce the issue. Open again if any more people encounter that problem again.

**Closed by openbullet** 2019-05-17 19:43 UTC
Labels: bug
