### ISSUE TITLE
[BUG] Tabulation and "IF", "BEGIN SCRIPT" and other commands

### ISSUE THREAD

**Issue by ostapvolanuk** [openbullet/openbullet#747] opened 2020-08-09 08:45 UTC
**Describe the bug**
When you using tabs, the script may skip part of the code. I found this bug when using "IF" and "BEGIN SCRIPT".

**To Reproduce**
Load test config and run:
```
##Without tabulation
BEGIN SCRIPT JavaScript
var a = 1+2;
var b = 'hello';
END SCRIPT -> VARS "a,b"

##With tabulation
BEGIN SCRIPT JavaScript
	var c = 1+2;
	var d = 'hello';
END SCRIPT -> VARS "c,d"
##As you can see, the second part of the code does not work, c and d are undefined
```

**Version**
1.2.2

**Comment by openbullet** [comment] 2020-08-09 19:45
This is due to the syntax of loliscript, in LS indentation = continuation of the last command, so `BEGIN SCRIPT JavaScript var c = 1+2; var d = 'hello';` is read as a whole. You should not indent the first line of the script, so something like
```
BEGIN SCRIPT JavaScript
var c = 1+2;
    var d = 'hello';
```
will be processed correctly. I'm closing this issue as this is a feature of the language and not a bug.

**Closed by openbullet** 2020-08-09 19:45 UTC
