### ISSUE TITLE
[BUG]With Auth Proxies

### ISSUE THREAD

**Issue by kazemmoridi** [openbullet/openbullet#683] opened 2020-05-21 10:11 UTC
**Describe the bug**
it's the same for me when i use selenium for "https://proxy.webshare.io auth proxies" it doesn't work and you need to write username,password yourself in the box that was opened in the browser, also , i use (http) before proxy and past it in the box.

**Comment by openbullet** [comment] 2020-05-21 12:21
Duplicate of https://github.com/openbullet/openbullet/issues/394

**Closed by openbullet** 2020-05-21 12:21 UTC
