### ISSUE TITLE
[BUG] Config already exists

### ISSUE THREAD

**Issue by lamjed001** [openbullet/openbullet#626] opened 2020-04-23 00:38 UTC
**Describe the bug**
when create new config and the name already used openbullet will be crushed

**To Reproduce**
1. Go to 'Configs'
2. Click on '(+) New'
3. Enter name already exists
4. Click accept
5. See error

**Version**
 - Version 1.2.1

**Comment by Cyber-Criminal** [comment] 2020-04-23 00:54
Duplicate of #579

**Closed** 2020-04-23 03:51 UTC
Labels: duplicate
