### ISSUE TITLE
[BUG] Runner suddenly "stops" itself

### ISSUE THREAD

**Issue by theman480** [openbullet/openbullet#378] opened 2019-10-07 16:35 UTC
So the tool is working perfectly than it's "stops" itself, I mean the running status keeps but there is no working on it:

https://prnt.sc/pg2bp5

**Comment by openbullet** [comment] 2020-03-03 01:47
Closing as the issue is too generic and OP didn't provide us with the right info to replicate it.

**Closed by openbullet** 2020-03-03 01:47 UTC
